version: '3.5'
services:
  db:
    image: postgres:11
    container_name: PhongVuong_postgres
    environment:
      POSTGRES_ROOT_PASSWORD: root
    volumes:
      - ./docker/db:/var/lib/postgresql/
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  app:
    container_name: PhongVuong_app
    depends_on:
      - 'db'
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db

volumes:
  postgres:
